
RESOURCE_FILE_PATH = "resources"
CHAT_FILE_PATH = f"{RESOURCE_FILE_PATH}/chats.json"
CREDENTIALS_FILE_PATH = f"{RESOURCE_FILE_PATH}/credentials.json"
FORWARD_CONFIG_FILE_PATH = f"{RESOURCE_FILE_PATH}/forwardConfig.json"
HISTORY_FILE_PATH = f"{RESOURCE_FILE_PATH}/history.json"

MEDIA_FOLDER_PATH = "media"

SESSION_FOLDER_PATH = "sessions"
SESSION_PREFIX_PATH = f"{SESSION_FOLDER_PATH}/session_"
